inherit_from: .rubocop_todo.yml

require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - 'spec/integration/test_repo/**/*'
    - 'spec/integration/test_repo_tree/**/*'
    - 'vendor/bundle/**/*'
  NewCops: enable
  TargetRubyVersion: 2.5

FactoryBot/AssociationStyle:
  EnforcedStyle: explicit

Layout/LineLength:
  Max: 140
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'nova_git_stats.gemspec'
    - 'spec/**/*'
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

RSpec/ExampleLength:
  Max: 21
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
Style/SymbolArray:
  EnforcedStyle: brackets
